openapi: 3.0.1
info:
  title: deleteApi
  description: API Definition of deleteApi
  version: 1.0.0
servers:
- url: http://localhost:8290/delete
paths:
  /:
    delete:
      responses:
        default:
          description: Default response
