openapi: 3.0.1
info:
  title: splitfileAPI
  description: API Definition of splitfileAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/filesplit
paths:
  /:
    get:
      responses:
        default:
          description: Default response
