name: Build and Deploy CARs to WSO2 MI

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build all CAR projects
        run: |
          for dir in */; do
            if [ -f "$dir/pom.xml" ]; then
              echo "🔧 Building: $dir"
              mvn -f "$dir/pom.xml" clean install -DskipTests
            fi
          done

      - name: Deploy CARs to WSO2 MI via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "**/target/*.car"
          target: "/your/mi/deployment/folder"
