name: Build and Deploy CARs (Local Volume Mount)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # You must run this on your own machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build all CAR projects
        run: |
          for dir in */; do
            if [ -f "$dir/pom.xml" ]; then
              echo "🔧 Building $dir"
              mvn -f "$dir/pom.xml" clean install -DskipTests --fail-never
            fi
          done

      - name: Copy .car files to local MI carbonapps folder
        run: |
          DEPLOY_DIR="/d/Sandip/wso2mi-4.2.0/wso2mi-4.2.0/repository/deployment/server/carbonapps"
          echo "Using deploy directory: $DEPLOY_DIR"

          for car in $(find . -name "*.car"); do
            echo "📦 Copying $car to $DEPLOY_DIR"
            cp "$car" "$DEPLOY_DIR"
          done

      - name: ✅ Done
        run: echo "CARs copied to WSO2 MI. It should auto-deploy shortly."
