name: Build and Deploy CARs (Windows + Docker Desktop)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # You must have a self-hosted runner running on your machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build all CAR projects
        run: |
          for /d %%D in (*) do (
            if exist "%%D\pom.xml" (
              echo Building %%D
              call mvn -f "%%D\pom.xml" clean install -DskipTests --fail-never
            )
          )
        shell: cmd

      - name: Copy .car files to WSO2 MI deployment folder
        run: |
          set "CARBONAPPS_DIR=D:\Sandip\wso2mi-4.2.0\wso2mi-4.2.0\repository\deployment\server\carbonapps"
          for /r %%f in (*.car) do (
            echo Copying %%f to %CARBONAPPS_DIR%
            copy "%%f" "%CARBONAPPS_DIR%"
          )
        shell: cmd

      - name: ✅ Done
        run: echo CAR deployment complete. WSO2 MI will auto-deploy them.
